services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${DATA_FOLDER}/db:/var/lib/postgresql/data/pgdata
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_PORT}

  http:
    build: http
    environment:
      PORT: ${PORT}
      GIN_MODE: release
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db

  nginx:
    build: nginx
    volumes:
      - ./static:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - http
