services:
  db:
    image: mariadb
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - ${DB_STORAGE}:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}

  auth:
    build: auth-mockup
    environment:
      ALLOWED_ORIGIN: http://${SERVER}:8080 http://${SERVER}
      API_PORT: ${API_PORT}
      COOKIE_NAME: ${COOKIE_NAME}
      COOKIE_LIFETIME_SEC: ${COOKIE_LIFETIME_SEC}
      COOKIE_SECRET: ${COOKIE_SECRET}
      TOKEN_SECRET: ${TOKEN_SECRET}
    ports: 
      - ${API_PORT}:${API_PORT}
    depends_on:
      db:
        condition: service_started

  client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        - VITE_AUTH_API=http://${SERVER}:${API_PORT}
    ports:
      - 80:80
    depends_on:
      - auth
