services:
  db:
    image: mariadb
    environment:
      MARIADB_USER: lipa_user
      MARIADB_PASSWORD: 12345
      MARIADB_ROOT_PASSWORD: 12345678
      MARIADB_DATABASE: lipa
    volumes:
      - ~/lipa-db:/var/lib/mysql
    ports:
      - 3306:3306

  auth:
    build: auth-mockup/
    ports: 
      - 3000:3000
    depends_on:
      - db

  client:
    build: client/
    ports:
      - 80:80
    depends_on:
      - auth
