services:
  db:
    image: mariadb
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - ${DB_STORAGE}:/var/lib/mysql
    ports:
      - 3306:3306

  auth:
    build: auth-mockup
    environment:
      ALLOWED_ORIGIN: http://${SERVER}:8080 http://${SERVER}
      PORT: ${AUTH_PORT}
      COOKIE_NAME: token
      COOKIE_LIFETIME_SEC: 86400
      COOKIE_SECRET: ${COOKIE_SECRET}
      TOKEN_SECRET: ${TOKEN_SECRET}
    ports: 
      - ${AUTH_PORT}:${AUTH_PORT}
    depends_on:
      db:
        condition: service_started

  client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        - VITE_AUTH_API=http://${SERVER}:${AUTH_PORT}
    ports:
      - 80:80
    depends_on:
      - auth
