services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${DATA_FOLDER}/db:/var/lib/postgresql/data/pgdata
    ports:
      - ${DB_PORT}:${DB_PORT}

  http:
    build: http
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
