services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: sample_user
      MARIADB_PASSWORD: 12345
      MARIADB_ROOT_PASSWORD: 12345
      MARIADB_DATABASE: lipa_db
    volumes:
      - /home/user/maria-data:/var/lib/mysql
    ports:
      - 3306:3306

  client:
    build: client/
    ports:
      - 80:80

  auth:
    build: auth-mockup/
    command: bun run src
    ports: 
      - 3000:3000
