services:
  db:
    image: mariadb
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - ${DB_STORAGE}:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:${PRODUCTION_PORT}
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  api:
    build: api
    environment:
      ALLOWED_ORIGIN: http://${SERVER}:${DEVELOPMENT_PORT} http://${SERVER}
      API_PORT: ${API_PORT}
      COOKIE_NAME: ${COOKIE_NAME}
      COOKIE_LIFETIME_SEC: ${COOKIE_LIFETIME_SEC}
      COOKIE_SECRET: ${COOKIE_SECRET}
      TOKEN_SECRET: ${TOKEN_SECRET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports: 
      - ${API_PORT}:${API_PORT}
    depends_on:
      db:
        condition: service_started

  client:
    build:
      context: client
      dockerfile: Dockerfile
      args:
        - VITE_API_URI=http://${SERVER}:${API_PORT}
    ports:
      - ${PRODUCTION_PORT}:${PRODUCTION_PORT}
    depends_on:
      - api
